# $Id$


# for face: ########################################################

PUB =  $(HOME)/public_html
CGIBIN = $(PUB)/cgi-bin

# local modifications ##############################################

LOCAL = uni:
COMMON = util:wash:control

DIRS = $(LOCAL)$(COMMON)

DEFINES = -DPOSIX=1

# common parts ############################################################

include Makefile







