# $Id$


# for face: ########################################################

PUB =  $(HOME)/public_html
CGIBIN = $(PUB)/cgi-bin

# local modifications ##############################################

LOCAL = uni:ws03/aus:
COMMON = util:wash:control:bridge:challenger:

DIRS = $(LOCAL)$(COMMON)

# common parts ############################################################

include Makefile







