# $Id$


# for face: ########################################################

PUB =  $(HOME)/public_html
CGIBIN = $(PUB)/cgi-bin

# local modifications ##############################################

LOCAL = uni:ws03/aus:
# COMMON = util:wash:control:bridge:challenger:
COMMON = util:wash:control

DIRS = $(LOCAL)$(COMMON)

DEFINES = -DPOSIX=1

# common parts ############################################################

include Makefile







